name: Bug report
description: Create a bug report
labels:
  - 'bug'

body:
  - type: textarea
    attributes:
      label: Expected
      description: What you expect to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual
      description: What you actually see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A step-by-step example (including code where applicable) of how to reproduce the bug. If you're using the Structurizr DSL, please add a full workspace definition (i.e. a model and views).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Version/build information
      description: Please list the version/build number(s) of the Structurizr software/library you are using.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Minor
        - Major
        - Critical
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - I have no budget and there's no rush, please fix this for free
        - I'm a Structurizr Patreon member (add details below or send a message on Patreon with a link to the issue)
        - I'm willing to pay for this fix (add details below)
        - I'm willing to fix this myself and raise a PR (please confirm approach first)
    validations:
      required: true 
  - type: textarea
    attributes:
      label: More information
      description: Please add anything else you think may be useful.

