blank_issues_enabled: false
contact_links:
  - name: Structurizr Slack
    url: https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg
    about: Community support is available via our Slack group, but please do not raise issues on here as they will likely be missed.

