name: Feature request
description: Create a feature request
labels:
  - 'enhancement'

body:
  - type: textarea
    attributes:
      label: Description
      description: A description of the feature request.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:    
      label: Priority
      options:
        - Low (I have no budget and there's no rush, please fix this for free)
        - Low (I'm willing to make a pull request - please confirm approach first)
        - High (we have a commercial support contract with Structurizr Limited)
    validations:
      required: true 
  - type: textarea
    attributes:
      label: More information
      description: Please add anything else you think may be useful.

